### ISSUE TITLE
Build on Netlify not working

### ISSUE THREAD

**Issue by 7Nic** [NextJSTemplates/play-nextjs#13]
An Prisma error ocurred on build

`7:35:02 AM:  ✓ Compiled successfully
7:35:02 AM:    Linting and checking validity of types ...
7:35:09 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
7:35:06 AM:    Collecting page data ...
7:35:08 AM: Prisma has detected that this project was built on Netlify CI, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
7:35:08 AM: Learn how: https://pris.ly/d/netlify-build
7:35:08 AM: PrismaClientInitializationError: Prisma has detected that this project was built on Netlify CI, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
7:35:08 AM: Learn how: https://pris.ly/d/netlify-build
7:35:08 AM:     at pa (/opt/build/repo/node_modules/@prisma/client/runtime/library.js:33:69)
7:35:08 AM:     at new r (/opt/build/repo/node_modules/@prisma/client/runtime/library.js:127:3083)
7:35:08 AM:     at 32021 (/opt/build/repo/.next/server/app/api/forgot-password/verify-token/route.js:1:1444)
7:35:08 AM:     at t (/opt/build/repo/.next/server/webpack-runtime.js:1:128)
7:35:08 AM:     at 353 (/opt/build/repo/.next/server/app/api/forgot-password/verify-token/route.js:1:440)
7:35:08 AM:     at t (/opt/build/repo/.next/server/webpack-runtime.js:1:128)
7:35:08 AM:     at r (/opt/build/repo/.next/server/app/api/forgot-password/verify-token/route.js:1:1546)
7:35:08 AM:     at /opt/build/repo/.next/server/app/api/forgot-password/verify-token/route.js:1:1577
7:35:08 AM:     at t.X (/opt/build/repo/.next/server/webpack-runtime.js:1:1206)
7:35:08 AM:     at /opt/build/repo/.next/server/app/api/forgot-password/verify-token/route.js:1:1559 {
7:35:08 AM:   clientVersion: '5.11.0',
7:35:08 AM:   errorCode: undefined
7:35:08 AM: }
7:35:08 AM: > Build error occurred
7:35:08 AM: Error: Failed to collect page data for /api/forgot-password/verify-token
7:35:08 AM:     at /opt/build/repo/node_modules/next/dist/build/utils.js:1258:15
7:35:08 AM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
7:35:08 AM:   type: 'Error'
7:35:08 AM: }`

**Comment by johurul-pimjo** [comment]
This is an issue of Prisma.

Please refer to their troubleshooting guide.

https://www.prisma.io/docs/orm/more/help-and-troubleshooting/netlify-caching-issue
