### ISSUE TITLE
Error when build on Vercel

### ISSUE THREAD

**Issue by blanktix** [NextJSTemplates/play-nextjs#15]
I'd just run the branch main of this repository in my initial Vercel project deployment but get this error on build stage
```
    at pa (/vercel/path0/node_modules/@prisma/client/runtime/library.js:33:69)
    at new r (/vercel/path0/node_modules/@prisma/client/runtime/library.js:127:3083)
    at 32021 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:72:163232)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
    at 13631 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1928)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
    at r (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:72:178177)
    at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:72:178208
    at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1206)
    at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:72:178190 {
  clientVersion: '5.11.0',
  errorCode: undefined
}
> Build error occurred
Error: Failed to collect page data for /api/auth/[...nextauth]
    at /vercel/path0/node_modules/next/dist/build/utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
Error: Command "npm run build" exited with 1
```

**Comment by avetise** [comment]
[14:13:02.330] Running build in Washington, D.C., USA (East) – iad1
[14:13:02.433] Cloning github.com/avetise/saas-trial (Branch: main, Commit: fa73df2)
[14:13:02.768] Previous build cache not available
[14:13:02.952] Cloning completed: 518.563ms
[14:13:03.252] Running "vercel build"
[14:13:03.699] Vercel CLI 39.2.5
[14:13:04.047] Installing dependencies...
[14:13:08.590] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[14:13:08.818] npm warn deprecated npmlog@5.0.1: This package is no longer supported.
[14:13:09.161] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[14:13:09.753] npm warn deprecated gauge@3.0.2: This package is no longer supported.
[14:13:09.758] npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
[14:13:09.999] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[14:13:10.030] npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
[14:13:10.037] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[14:13:12.509] npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
[14:13:23.358] 
[14:13:23.358] added 534 packages in 19s
[14:13:23.358] 
[14:13:23.358] 208 packages are looking for funding
[14:13:23.358]   run `npm fund` for details
[14:13:23.382] Detected Next.js version: 14.2.17
[14:13:23.389] Running "npm run build"
[14:13:23.544] 
[14:13:23.544] > play-nextjs@2.0.0 build
[14:13:23.545] > next build
[14:13:23.545] 
[14:13:24.493] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[14:13:24.493] This information is used to shape Next.js' roadmap and prioritize features.
[14:13:24.493] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[14:13:24.494] https://nextjs.org/telemetry
[14:13:24.494] 
[14:13:24.615]   ▲ Next.js 14.2.17
[14:13:24.615] 
[14:13:24.692]    Creating an optimized production build ...
[14:13:37.765] 
[14:13:37.765] [1m[33mwarn[39m[22m - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
[14:13:37.767] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.767] 
[14:13:37.767] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
[14:13:37.767] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:41.514]  ✓ Compiled successfully
[14:13:41.515]    Linting and checking validity of types ...
[14:13:47.579]    Collecting page data ...
[14:13:48.129] Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[14:13:48.129] 
[14:13:48.129] Learn how: https://pris.ly/d/vercel-build
[14:13:48.130] PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[14:13:48.130] 
[14:13:48.130] Learn how: https://pris.ly/d/vercel-build
[14:13:48.130]     at Ba (/vercel/path0/node_modules/@prisma/client/runtime/library.js:33:69)
[14:13:48.131]     at new t (/vercel/path0/node_modules/@prisma/client/runtime/library.js:130:739)
[14:13:48.131]     at 8690 (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:771)
[14:13:48.131]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[14:13:48.131]     at 10583 (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:1:1045)
[14:13:48.131]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[14:13:48.131]     at t (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:873)
[14:13:48.131]     at /vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:908
[14:13:48.131]     at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1206)
[14:13:48.131]     at /vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:886 {
[14:13:48.131]   clientVersion: '5.22.0',
[14:13:48.131]   errorCode: undefined
[14:13:48.131] }
[14:13:48.133] 
[14:13:48.133] > Build error occurred
[14:13:48.133] Error: Failed to collect page data for /api/forgot-password/reset
[14:13:48.133]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
[14:13:48.133]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
[14:13:48.133]   type: 'Error'
[14:13:48.133] }
[14:13:48.173] Error: Command "npm run build" exited with 1
[14:13:48.580]

**Comment by avetise** [comment]
[14:13:02.330] Running build in Washington, D.C., USA (East) – iad1
[14:13:02.433] Cloning github.com/XXXXXXX
[14:13:02.768] Previous build cache not available
[14:13:02.952] Cloning completed: 518.563ms
[14:13:03.252] Running "vercel build"
[14:13:03.699] Vercel CLI 39.2.5
[14:13:04.047] Installing dependencies...
[14:13:08.590] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[14:13:08.818] npm warn deprecated npmlog@5.0.1: This package is no longer supported.
[14:13:09.161] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[14:13:09.753] npm warn deprecated gauge@3.0.2: This package is no longer supported.
[14:13:09.758] npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
[14:13:09.999] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[14:13:10.030] npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
[14:13:10.037] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[14:13:12.509] npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
[14:13:23.358] 
[14:13:23.358] added 534 packages in 19s
[14:13:23.358] 
[14:13:23.358] 208 packages are looking for funding
[14:13:23.358]   run `npm fund` for details
[14:13:23.382] Detected Next.js version: 14.2.17
[14:13:23.389] Running "npm run build"
[14:13:23.544] 
[14:13:23.544] > play-nextjs@2.0.0 build
[14:13:23.545] > next build
[14:13:23.545] 
[14:13:24.493] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[14:13:24.493] This information is used to shape Next.js' roadmap and prioritize features.
[14:13:24.493] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[14:13:24.494] https://nextjs.org/telemetry
[14:13:24.494] 
[14:13:24.615]   ▲ Next.js 14.2.17
[14:13:24.615] 
[14:13:24.692]    Creating an optimized production build ...
[14:13:37.765] 
[14:13:37.765] [1m[33mwarn[39m[22m - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
[14:13:37.766] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.766] 
[14:13:37.766] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
[14:13:37.767] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:37.767] 
[14:13:37.767] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
[14:13:37.767] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[14:13:41.514]  ✓ Compiled successfully
[14:13:41.515]    Linting and checking validity of types ...
[14:13:47.579]    Collecting page data ...
[14:13:48.129] Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[14:13:48.129] 
[14:13:48.129] Learn how: https://pris.ly/d/vercel-build
[14:13:48.130] PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[14:13:48.130] 
[14:13:48.130] Learn how: https://pris.ly/d/vercel-build
[14:13:48.130]     at Ba (/vercel/path0/node_modules/@prisma/client/runtime/library.js:33:69)
[14:13:48.131]     at new t (/vercel/path0/node_modules/@prisma/client/runtime/library.js:130:739)
[14:13:48.131]     at 8690 (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:771)
[14:13:48.131]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[14:13:48.131]     at 10583 (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:1:1045)
[14:13:48.131]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[14:13:48.131]     at t (/vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:873)
[14:13:48.131]     at /vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:908
[14:13:48.131]     at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1206)
[14:13:48.131]     at /vercel/path0/.next/server/app/api/forgot-password/reset/route.js:7:886 {
[14:13:48.131]   clientVersion: '5.22.0',
[14:13:48.131]   errorCode: undefined
[14:13:48.131] }
[14:13:48.133] 
[14:13:48.133] > Build error occurred
[14:13:48.133] Error: Failed to collect page data for /api/forgot-password/reset
[14:13:48.133]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
[14:13:48.133]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
[14:13:48.133]   type: 'Error'
[14:13:48.133] }
[14:13:48.173] Error: Command "npm run build" exited with 1
[14:13:48.580]

**Comment by johurul-pimjo** [comment]
Thanks for pointing it out.

We're working on rolling a patch for it.

At the moment in your `package.json` file, change the build command to:
`"build": "prisma generate && next build"`.

Alternatively, you can also add a new script without changing the build command:
`"postinstall": "prisma generate"`

The caveat to the last approach is that it only works with npm.

Before building the application the `prisma generate` needs to run to generate prisma-client. 

In both approach before building the application we are running `prisma generate` to generate prisma-client. This ensures that during build for SSR pages that are making db call using prisma-client does not throw errors.
